name: $(date:yyyyMMdd).$(rev:rr)

variables:
- group: azure.vars
- { name: id, value: shark_tank }
- { name: directory, value: SPC-2021/api/shark_tank }
- { name: namespace, value: SharkTank }
- { name: webapp, value: api }

trigger:
  branches:
    include:
    - feature
  paths:
    include:
    - SPC-2021/.azure/pipes/api.yaml
    - SPC-2021/.azure/pipes/deploy.yaml
    - SPC-2021/api/shark_tank
  tags:
    include:
    - '*'


pr:
  branches:
    include:
    - master
  paths:
    include:
    - SPC-2021/.azure/pipes/api.yaml
    - SPC-2021/.azure/pipes/deploy.yaml
    - SPC-2021/api/shark_tank

stages:
- template: ../../../pipes/api.yaml
  parameters:
    id: $(id)
- template: ../../../pipes/deploy.yaml
  parameters:
    id: $(id)