# angular :: azure-devops

parameters:
  id: ''

stages:
- stage: Build_and_Test
  pool:
    vmImage: 'ubuntu-latest'
  variables: 
    appDir: santa/src
    buildConfiguration: 'Release'
  jobs:
################################################################################################################################# BUILD
  - job: Build
    steps:
    - script: echo Started Build
      condition: always()

    - task: DotNetCoreCLI@2
      displayName: Dotnet Build
      continueOnError: false
      inputs:
        command: 'build'
        workingDirectory: '$(appDir)'
        zipAfterPublish: true
        
    - task: DotNetCoreCLI@2
      displayName: Dotnet Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        zipAfterPublish: true
        workingDirectory: '$(appDir)'
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'

    - task: PublishBuildArtifacts@1
      displayName: Publish Dotnet Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
############################################################################################################################# DEPLOY
- stage: Deploy
  dependsOn:
  - Build_and_Test
  condition: succeeded()
  jobs:
  - job: Deploy_API
    steps:
    - script: echo Publishing steps started

    - task: DownloadBuildArtifacts@0
      displayName: Retrieving Build Artifacts
      inputs:
        buildType: 'current'
        downloadType: 'single'
        artifactName: 'drop'
        downloadPath: '$(System.ArtifactsDirectory)'
    - task: CopyFiles@2
      inputs:
        SourceFolder: '$(System.ArtifactsDirectory)'
        Contents: '**'
        TargetFolder: '$(System.DefaultWorkingDirectory)'
    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure Portal Plan(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        appType: 'webApp'
        WebAppName: 'dev-santaponecentral-api'
        packageForLinux: '$(System.DefaultWorkingDirectory)/**/*.zip'