# santa :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

trigger:
  branches:
    include:
    - feature
  paths:
    include:
    - .azure/dev/api.yaml
    - santa/src

pr:
  branches:
    exclude:
    - "*"

stages:
- template: ../../.azure/dev/api.yaml
  parameters:
    id: $(id)
