# santa :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

trigger:
  branches:
    include:
    - feature
  paths:
    include:
    - .azure/stages/angular.yaml
    - .azure/stages/angular.yaml
    - santa/AngularClient/santa-pone-central

stages:
- template: ../../../.azure/build/angular.yaml
  parameters:
    id: $(id)
