# santa :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
  paths:
    include:
    - .azure/stages/deploy.yml
    - .azure/stages/angular.yml
    - santa/AngularClient/santa-pone-central

pr:
  branches:
    include:
    - master
  paths:
    include:
    - .azure/stages/deploy.yaml
    - .azure/stages/angular.yaml
    - santa/AngularClient/santa-pone-central

stages:
- template: ../../.azure/stages/angular.yml
  parameters:
    id: $(id)
- template: ../../.azure/stages/deploy.yml
  parameters:
    id: $(id)
