# santa :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
  paths:
    include:
    - .azure/stages/aspnet.yml
    - santa/AngularClient/santa-pone-central

pr:
  branches:
    include:
    - master
  paths:
    include:
    - .azure/stages/aspnet.yml
    - santa/AngularClient/santa-pone-central

pool:
  vmImage: 'ubuntu-latest'

stages:
- template: ../../.azure/stages/angular.yml
  parameters:
    id: $(id)
- template: ../../.azure/stages/deploy.yml
  parameters:
    id: $(id)
