# santa :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
  paths:
    include:
    - .azure/stages/angular.yaml
    - santa/AngularClient/santa-pone-central

pr:
  branches:
    exclude:
    - master

stages:
- template: ../../.azure/stages/angular.yaml
  parameters:
    id: $(id)
