# santa :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

trigger:
  branches:
    include:
    - master
  tags:
    include:
    - '*'
  paths:
    include:
    - .azure/stages/api.yaml
    - santa/src

# pr:
#   branches:
#     include:
#     - master
#   paths:
#     include:
#     - .azure/stages/api.yaml
#     - santa/src

stages:
- template: ../../.azure/stages/api.yaml
  parameters:
    id: $(id)
