# santa :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

pr:
  branches:
    include:
    - master
    tags:
      include:
      - '*'
    paths:
      include:
      - .azure/stages/angular.yaml
      - santa/AngularClient/santa-pone-central

stages:
- template: ../../.azure/stages/angularPRBuild.yaml
  parameters:
    id: $(id)
