# santa :: azure-devops

name: $(date:yyyyMMdd).$(rev:rr)

trigger:
  branches:
    include:
    - master
  paths:
    include:
    - .azure/prod/api.yaml
    - santa/src

pr:
  branches:
    exclude:
    - master

stages:
- template: ../../../.azure/prod/api.yaml
  parameters:
    id: $(id)
