# angular :: azure-devops

parameters:
  id: ''

stages:
- stage: build
  displayName: build
  jobs:
  - job: build_angular
    displayName: build-angular
    pool:
      vmImage: ubuntu-18.04
    steps:
    - task: UseNode@1
      inputs:
        version: '12.13'
      displayName: node
    - script: npm ci
      displayName: npm install
      workingDirectory: $(directory)
    - script: npm run lint
      displayName: npm lint
      workingDirectory: $(directory)
    - script: npm run build
      displayName: npm build
      workingDirectory: $(directory)
    - script: npm test
      displayName: npm test
      workingDirectory: $(directory)
- stage: pack
  displayName: pack
  dependsOn: build
  condition: and(succeeded('build'), or(
    eq(variables['Build.SourceBranch'], 'refs/heads/master'),
    startsWith(variables['Build.SourceBranch'], 'refs/tags')))
  jobs:
  - job: pack_angular
    displayName: pack-angular
    pool:
      vmImage: ubuntu-18.04
    steps:
    - task: DownloadSecureFile@1
      displayName: angular environment::dev
      condition: and(succeeded(), eq(variables['Build.SourceBranch'], 'refs/heads/master'))
      inputs:
        secureFile: angular.${{ parameters.id }}.dev.ts
      name: ngenvdev
    - task: DownloadSecureFile@1
      displayName: angular environment::stg
      condition: and(succeeded(), startsWith(variables['Build.SourceBranch'], 'refs/tags'))
      inputs:
        secureFile: angular.${{ parameters.id }}.stg.ts
      name: ngenvstg