# angular :: azure-devops

parameters:
  id: ''

stages:
- stage: build
  displayName: build
  jobs:
  - job: build_angular
    displayName: build-angular
    pool:
      vmImage: ubuntu-18.04
    steps:
    - task: UseNode@1
      inputs:
        version: '12.13'
      displayName: node
    - script: npm ci
      displayName: npm install
      workingDirectory: $(directory)
    - script: npm run lint
      displayName: npm lint
      workingDirectory: $(directory)
    - script: npm run build
      displayName: npm build
      workingDirectory: $(directory)
    - script: npm test
      displayName: npm test
      workingDirectory: $(directory)