# angular :: azure-devops

parameters:
  id: ''

stages:
- stage: Deploy_Angular
  dependsOn:
  - Build_and_Test_Master
  pool:
    vmImage: 'ubuntu-latest'
  variables: 
    appDir: AngularClient
  jobs:
  - job: Build_And_Deploy_Angular
    steps:
    - script: echo Beginning process
    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: npm ci
      displayName: npm install
      workingDirectory: $(appDir)

    - script: npx ng build --prod
      displayName: ng build
      workingDirectory: $(appDir)

    - script: npx ng test --browsers ChromeHeadless --no-watch --code-coverage
      displayName: ng test
      workingDirectory: $(appDir)

    
        #packageForLinux: '$(appDir)/dist/*'

########################################################################################################################### WEB APP DEPLOYED