# angular :: azure-devops

parameters:
  id: ''

stages:
- stage: Build_and_Test
  pool:
    vmImage: 'windows-latest'
  variables: 
    appDir: santa/src
    buildConfiguration: 'Release'
  jobs:
################################################################################################################################# BUILD
  - job: Build
    steps:
    - script: echo Started Build
      condition: always()

    - task: DotNetCoreCLI@2
      displayName: Dotnet Build
      continueOnError: false
      inputs:
        command: 'build'
        workingDirectory: '$(appDir)'

    #- task: DotNetCoreCLI@2
    #  continueOnError: false
    #  inputs:
    #    command: 'test'
    #    projects: '**/*Test/*.csproj'
    #    workingDirectory: '$(appDir)'
    #    arguments: '--configuration $(buildConfiguration) --collect "Code coverage"'

    - task: DotNetCoreCLI@2
      displayName: Dotnet Publish
      inputs:
        command: 'publish'
        publishWebProjects: true
        zipAfterPublish: true
        workingDirectory: '$(appDir)'
        arguments: '--configuration $(BuildConfiguration) --output $(Build.ArtifactStagingDirectory)'
        
    
    - task: PublishBuildArtifacts@1
      displayName: Publish Dotnet Artifacts
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'