# deploy :: azure-devops

parameters:
  id: ''
 
stages:
- stage: dev
  displayName: deploy::dev
  dependsOn: pack
  condition: and(succeeded('pack'), startsWith(variables['Build.SourceBranch'], 'refs/heads/master'))
  jobs:
  - job: deploy_dev
    displayName: deploy::dev
    pool:
      vmImage: ubuntu-18.04
    steps: