# angular :: azure-devops

parameters:
  id: ''

stages:
- stage: Deploy_Angular
  pool:
    vmImage: 'windows-latest'
  variables: 
    appDir: santa/AngularClient/santa-pone-central
  jobs:
  - job: Build_And_Deploy_Angular_Dev_Build
    steps:
    - script: echo Beginning process

    - task: NodeTool@0
      inputs:
        versionSpec: '12.x'
      displayName: 'Install Node.js'

    - script: npm ci
      displayName: npm install
      workingDirectory: '$(appDir)'

    - script: npx ng build --configuration="dev"
      displayName: ng build
      workingDirectory: $(appDir)

    - task: AzureRmWebAppDeployment@4
      inputs:
        ConnectionType: 'AzureRM'
        azureSubscription: 'Azure Portal Plan(92f11ea8-1c99-4c20-a2a9-6a3aed18291d)'
        appType: 'webApp'
        WebAppName: 'dev-santaponecentral'
        packageForLinux: '$(appDir)/dist/*'

########################################################################################################################### WEB APP DEPLOYED