name: Dev - Profile API Docker Image Build and Push to Hub

on:
  push:
    branches: 
    - feature
    paths:
    - 'SPC-2021/api/profile/**'
    - '.github/workflows/dev-profileapi-docker.yml'
    
env:
  API_PATH: 'SPC-2021/api/profile'
  API_IMAGE_NAME: 'profileapi'

jobs:
  build-and-push-dev-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #Step 0
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    #Step 1
    - name: Build the Docker image
      run: cd ${{ env.API_PATH }} && docker build . --file .docker/Dockerfile --tag ${{ secrets.DH_USERNAME }}/spc-${{ env.API_IMAGE_NAME }}:dev
    #Step 3
    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DH_USERNAME }}/spc-${{ env.API_IMAGE_NAME }}:dev
