name: Dev Site - Angular Docker Image Build and Push to Hub

on:
  push:
    branches: 
    - feature
    paths:
    - 'SPC-2021/angular/**'
    - '.github/workflows/dev-site-docker.yml'
    
env:
  ANGULAR_PATH: 'SPC-2021/angular'
  ANGULAR_IMAGE_NAME: 'spc-2021'

jobs:
  build-and-push-dev-image:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    #Step 0
    - name: Docker Login
      uses: docker/login-action@v1.8.0
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
        # Log out from the Docker registry at the end of a job
        logout: true
    #Step 1
    - name: Build the Docker image
      run: cd ${{ env.ANGULAR_PATH }} && docker build . --file .docker/Dockerfile.Dev --tag ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.ANGULAR_IMAGE_NAME }}:dev
    #Step 3
    - name: Push image to Docker Hub
      run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.ANGULAR_IMAGE_NAME }}:dev
